services:
  - type: web
    runtime: node
    name: coviac-asbl
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NITRO_PRESET
        value: render-com
      - key: NODE_VERSION
        value: "24"
      - key: HOST
        value: 0.0.0.0
