services:
  - type: web
    runtime: bun
    name: coviac-asbl
    plan: free
    buildCommand: bun install --frozen-lockfile && bun run build
    startCommand: bun run start
    envVars:
      - key: NITRO_PRESET
        value: render-com
      - key: HOST
        value: 0.0.0.0
